# Travis CI build file for Package-Builder.
# Package-Builder runs on OS X and Linux (Ubuntu).

before_install:
- git clone https://github.com/IBM-Swift/Package-Builder.git

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.2
    - os: osx
      osx_image: xcode9.2
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: JAZZY_ELIGIBLE=true
    - os: osx
      osx_image: xcode10
      sudo: required
      env: SWIFT_SNAPSHOT=4.2

script:
  # Set up build structure for test projects
  - mv tests/library ../library
  - mv tests/executable ../executable
  - cp -R ./ ../library/Package-Builder
  - cp -R ./ ../executable/Package-Builder
  - cp -R ../executable ../executable-no-swift-version
  - rm ../executable-no-swift-version/.swift-version
  # This tests Package-Builder with a library
  - cd ../library
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR/library
  # This tests Package-Builder with an executable
  - cd ../executable
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR/executable
  # Test building a package that does not have a .swift-version file
  - cd ../executable-no-swift-version
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR/executable-no-swift-version
